### ISSUE TITLE
Some audio files display "none" or are blank

### ISSUE THREAD

**Issue by sbogard** [Tutt-Library/digital-cc#27]
ex. 6986

**Comment by sbogard** [comment]
This is still an issue and is a problem not only with the old audio but also with new audio being ingested. The audio plays in Islandora. It is a big issue for the Music Library files

**Comment by jermnelson** [comment]
Tested accessing both audio file(s) for these PIDs under both Chrome and Firefox browers for Windows 7 and MacOS:

From the Cobos Collection:

1. https://digitalccbeta.coloradocollege.edu/pid/coccc:6994 (both WAV and mp3)

1. https://digitalccbeta.coloradocollege.edu/pid/coccc:7736 (both WAV and mp3)

From Oral History Collections:

1. https://digitalccbeta.coloradocollege.edu/pid/coccc:3054 (mp3)

1. https://digitalccbeta.coloradocollege.edu/pid/coccc:6053 (mp3)

Please verify that these datastreams are accessable before closing this issue.
