### ISSUE TITLE
Recordings objects should display label and not as a PROXY_MP3

### ISSUE THREAD

**Issue by jermnelson** [Tutt-Library/digital-cc#35]
Annette reported issue with a display of content with the various wav recording datastreams not being displayed correctly, for example this PID 
https://digitalccbeta.coloradocollege.edu/pid/coccc:11216 is a compound object with a long list of child wav files, each with a different label but now being displayed with all PROXY_MP3.

**Comment by amegneys** [comment]
Why do the child wav files not display in correct order (PID 11216)?
