### ISSUE TITLE
Some PDF's show as Internal Server Error

### ISSUE THREAD

**Issue by sbogard** [Tutt-Library/digital-cc#37]
Tested on Chrome on Mac and PC ex PIDs: 27265 and 27259. Both are functional on Islandora

**Comment by jermnelson** [comment]
Should now be fixed, tested and accessed https://digitalccbeta.coloradocollege.edu/pid/coccc:27265 and https://digitalccbeta.coloradocollege.edu/pid/coccc:2759 under the following combinations:

- Chrome and Firefox: Windows 7
- Chrome and Firefox: MacOS

Under Digital CC version  1.0.1, Elasticsearch Index from 2017-03-23 19:12:57. (See https://digitalccbeta.coloradocollege.edu/about to get this information)

Verify before closing this issue.
