### ISSUE TITLE
Preview images do not list their file names.

### ISSUE THREAD

**Issue by sbogard** [Tutt-Library/digital-cc#38]
ex. COCCC:5874 
This makes it difficult to tell which file you are looking at when you are viewing a compound object with numerous media files. 

Chrome, PC and MAC

**Comment by jermnelson** [comment]
For COCCC:5874 compound object, the current filename in Fedora is being used for all of the media files. If we want more descriptive filenames, we will need to change the LABEL for the OBJ media datastreams. This is a more of a metadata quality issue than a digitalcc beta display issue.
