### ISSUE TITLE
Image thumbnails don't show up next to collection titles except on front page.

### ISSUE THREAD

**Issue by sbogard** [Tutt-Library/digital-cc#7]
All that shows up is the broken image symbol. I believe this is because in the islandora DigitalCC there are just folder icons next to these, should we create thumbnails for them?

**Comment by jermnelson** [comment]
Yes, we should have some default thumbnails to use if the thumbnail is not present in Fedora. If you can come up with some examples, we add the logic into the view.

**Comment by sbogard** [comment]
fixed with creation of a default thumbnail
