### ISSUE TITLE
When indexing a PID, creates a duplicate link

### ISSUE THREAD

**Issue by mjhartmann86** [Tutt-Library/digital-cc#72]
Indexing through Fedora causes a duplicate link to the PID to appear in the beta.

In the testdocker, duplicates of collections do not show up (even if they appear in beta), but duplicates of individual objects still appear.
![individual pid dupe](https://user-images.githubusercontent.com/35468508/38832279-49abe052-417f-11e8-86b4-574ceae3529b.jpg)
![collection dupe](https://user-images.githubusercontent.com/35468508/38832284-4cc55c28-417f-11e8-99d1-8d0e2a19b2e2.jpg)
![testdocker individual pid dupe](https://user-images.githubusercontent.com/35468508/38832288-4eb53c10-417f-11e8-8067-f201bd981fc4.jpg)
![testdocker collection dupe](https://user-images.githubusercontent.com/35468508/38832289-500b5b3a-417f-11e8-84c1-6c50d900d6a3.jpg)

**Comment by mjhartmann86** [comment]
PID for the Cobos collection is coccc:6841
PID for the Adolordio obj is coccc:7367

**Comment by jermnelson** [comment]
Just updated Fedora Utilities with commit https://github.com/Tutt-Library/fedora38-utilities/commit/2a0960098275475a610d018af106907c9ab07801 that fixes this problem. Needs final testing to close issue.

**Comment by mjhartmann86** [comment]
Reindexing no longer creates duplicate links, however there is still a duplicate link of the Cobos Collection (PID coccc:6841) that is still visible in the Southwest collection (PID coccc:5881).

**Comment by jermnelson** [comment]
Currently https://digitalccbeta.coloradocollege.edu/pid/coccc:5881 does not duplicate the Cobos Collection  for me. Try clearing your web browser cache and reload the Southwest Collection. 

Closing this issue for now.
