### ISSUE TITLE
Ordering of objects

### ISSUE THREAD

**Issue by amegneys** [Tutt-Library/digital-cc#73]
Ordering of child objects in Beta does not mirror order in Islandora. This is in reference to file we checked during our workshop today.  Turns out, the order is correct in Islandora, so there is nothing to correct.
Order in Islandora: 
![image](https://user-images.githubusercontent.com/32716225/38837858-e30ba10e-4190-11e8-9a15-efb9055cbd01.png)

Order in Beta:
![image](https://user-images.githubusercontent.com/32716225/38837983-66de29b6-4191-11e8-8a69-92062b3a876f.png)

Note:  The recital pdf "2017-04-26 Jake Sabetta.pdf" should be 2nd (it is 8th) and the first audio recording "All it takes" should be 3rd (it is 10th).

Same thing with this one: correct order in Islandora:
![image](https://user-images.githubusercontent.com/32716225/38838380-0cd385f4-4193-11e8-86a3-e83440cd0926.png)
Incorrect order in Beta:
![image](https://user-images.githubusercontent.com/32716225/38838403-28b3a678-4193-11e8-8e3a-e62b01d08b1e.png)

Annette Megneys
x6960

**Comment by jermnelson** [comment]
Ordering now follows ordering in RELS-EXT, fixed in https://digitalccbeta.coloradocollege.edu/pid/coccc:27700.
