### ISSUE TITLE
2008-2009 Econ Thesis Collection showing thumbnails and nothing else. 

### ISSUE THREAD

**Issue by sbogard** [Tutt-Library/digital-cc#76]
coccc:23
There are a couple theses that show and then the rest are only thumbnails, no titles, no creator info, just thumbnails. In Islandora the information is present but the theses are not viewable. The PDFs are present and can be downloaded from the datastreams.

**Comment by jermnelson** [comment]
The thesis that are missing information had an incorrect mods namespace of *http://www.loc.gov/standards/mods/v3* changed to correct namespace of *http://www.loc.gov/mods/v3* and reindexing fixed errors in the https://digitalccbeta.coloradocollege.edu/pid/coccc:23 collection.
