### ISSUE TITLE
Link error in notifications

### ISSUE THREAD

**Issue by amegneys** [Tutt-Library/digital-cc#77]
The link in email notifications when a thesis is submitted opens in Islandora.  See latest submission by Mary Nguyen. (pdf is not viewable, but okay in BETA.)

From: <digitalarchives@coloradocollege.edu>
To: <mh_nguyen@coloradocollege.edu,rbanagale@coloradocollege.edu,mgrace@coloradocollege.edu,lgregory@coloradocollege.edu,amegneys@coloradocollege.edu>
Subject: Mozart's Grand Tour in Italy  submitted to DACC

Mozart's Grand Tour in Italy  successfully submitted to Colorado College Tutt Library Digital Archives available at https://digitalcc.coloradocollege.edu/islandora/object/coccc:30078
Mozart's Grand Tour in Italy  successfully submitted to Colorado College Tutt Library Digital Archives available at **https://digitalcc.coloradocollege.edu/islandora/object/coccc:30078**

**Comment by jermnelson** [comment]
This was a deliberate decision to display the old Islandora link until we move from digitalccbeta.coloradocolelge.edu to digitalcc.coloradocollege.edu. This move is planed for summer 2018.

**Comment by amegneys** [comment]
That’s good to know, but in the case of PID 30078, the pdf is not displaying in Islandora.
Annette
