### ISSUE TITLE
PID 29797 (Senior thesis)

### ISSUE THREAD

**Issue by amegneys** [Tutt-Library/digital-cc#78]
MP4 error message "Video playback aborted due to network error" 
![image](https://user-images.githubusercontent.com/32716225/39878765-62dd3ff2-5436-11e8-9dcb-68a689e98860.png)

This happens in Firefox.  Plays normally in Google Chrome.

**Comment by jermnelson** [comment]
This isn't a bug on the server-side, video plays on both Firefox 59.03 and Chrome on Windows 10. Should look at local Firefox installation.

**Comment by amegneys** [comment]
We do have Firefox 59.03 on our computers. The error message appears after 25 to 35 seconds.  It doesn’t happen at the beginning.
Annette
